imageVerification:
  enabled: true
  policyName: redacta-verify-signed-images
  namespace: redacta
  failureAction: Enforce
  registry: acrredacta7t9.azurecr.io
  issuer: https://token.actions.githubusercontent.com
  rekorUrl: https://rekor.sigstore.dev
  subjects:
    - https://github.com/babasoyturan/Redacta/.github/workflows/backend-ci-cd.yml@refs/heads/dev
    - https://github.com/babasoyturan/Redacta/.github/workflows/backend-ci-cd.yml@refs/heads/main
    - https://github.com/babasoyturan/Redacta/.github/workflows/frontend-ci-cd.yml@refs/heads/dev
    - https://github.com/babasoyturan/Redacta/.github/workflows/frontend-ci-cd.yml@refs/heads/main

monitoring:
  serviceMonitor:
    enabled: true
    apiVersion: azmonitoring.coreos.com/v1
    interval: 30s
    scrapeTimeout: 10s
    kyverno:
      enabled: true
      namespace: kyverno
      port: metrics-port
    argocd:
      enabled: true
      namespace: argocd
      port: metrics
    certManager:
      enabled: true
      namespace: cert-manager
      port: http-metrics
