apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-development
  namespace: argocd
spec:
  project: redacta-development
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: 3.8.2
    helm:
      releaseName: kyverno
      values: |
        admissionController:
          replicas: 1
          serviceAccount:
            annotations:
              azure.workload.identity/client-id: f35cf3a1-dc2c-4b3e-9245-22307ade9122
          podLabels:
            azure.workload.identity/use: "true"
        backgroundController:
          enabled: false
        cleanupController:
          enabled: false
        reportsController:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
