{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "redacta-infra.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.values.postgresPassword | quote }}
  keycloak-admin-username: {{ .Values.secrets.values.keycloakAdminUsername | quote }}
  keycloak-admin-password: {{ .Values.secrets.values.keycloakAdminPassword | quote }}
{{- end }}
