{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "redacta.labels" . | nindent 4 }}
type: Opaque
stringData:
  datasource-username: {{ .Values.secrets.values.datasourceUsername | quote }}
  datasource-password: {{ .Values.secrets.values.datasourcePassword | quote }}
  keycloak-client-secret: {{ .Values.secrets.values.keycloakClientSecret | quote }}
  keycloak-admin-username: {{ .Values.secrets.values.keycloakAdminUsername | quote }}
  keycloak-admin-password: {{ .Values.secrets.values.keycloakAdminPassword | quote }}
  openai-api-key: {{ .Values.secrets.values.openaiApiKey | quote }}
{{- end }}
