{{- if .Values.serviceAccount.create }}
{{- range $component := list "documentService" "authenticationService" "anonymizationService" "genaiService" "keycloak" }}
{{- if or (ne $component "keycloak") $.Values.keycloak.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "redacta.componentServiceAccountName" (dict "root" $ "component" $component) }}
  labels:
    {{- include "redacta.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component | kebabcase }}
  annotations:
    {{- include "redacta.workloadIdentityAnnotation" (dict "root" $ "component" $component) | nindent 4 }}
    {{- with $.Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
