secrets:
  create: true
  values:
    datasourceUsername: "<postgres-username>"
    datasourcePassword: "<postgres-password>"
    keycloakClientSecret: "<keycloak-backend-client-secret>"
    keycloakAdminUsername: "<keycloak-admin-username>"
    keycloakAdminPassword: "<keycloak-admin-password>"
    openaiApiKey: "<openai-api-key>"

documentService:
  storageLocation: /tmp/redacta-uploads

genaiService:
  localFallback: false
  openaiModel: gpt-4.1-mini

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
