frontend:
  image:
    repository: acrredacta7t9.azurecr.io/redacta-frontend
    tag: cf0f7cf-16-1

documentService:
  image:
    repository: acrredacta7t9.azurecr.io/redacta-document-service
    tag: ac8b569

authenticationService:
  image:
    repository: acrredacta7t9.azurecr.io/redacta-authentication-service
    tag: ac8b569

anonymizationService:
  image:
    repository: acrredacta7t9.azurecr.io/redacta-anonymization-service
    tag: ac8b569

genaiService:
  image:
    repository: acrredacta7t9.azurecr.io/redacta-genai-service
    tag: ac8b569
