frontend:
  image:
    repository: acrredacta7t9.azurecr.io/redacta-frontend
    tag: cf761cf-49-1

documentService:
  image:
    repository: acrredacta7t9.azurecr.io/redacta-document-service
    tag: 45cc1eb-64-1

authenticationService:
  image:
    repository: acrredacta7t9.azurecr.io/redacta-authentication-service
    tag: 45cc1eb-64-1

anonymizationService:
  image:
    repository: acrredacta7t9.azurecr.io/redacta-anonymization-service
    tag: 45cc1eb-64-1

genaiService:
  image:
    repository: acrredacta7t9.azurecr.io/redacta-genai-service
    tag: 45cc1eb-64-1
