frontend:
  image:
    repository: acrredacta7t9.azurecr.io/redacta-frontend
    tag: replace-me

documentService:
  image:
    repository: acrredacta7t9.azurecr.io/redacta-document-service
    tag: replace-me

authenticationService:
  image:
    repository: acrredacta7t9.azurecr.io/redacta-authentication-service
    tag: replace-me

anonymizationService:
  image:
    repository: acrredacta7t9.azurecr.io/redacta-anonymization-service
    tag: replace-me

genaiService:
  image:
    repository: acrredacta7t9.azurecr.io/redacta-genai-service
    tag: replace-me
