apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redacta-app-local
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: redacta-local
  source:
    repoURL: git@github.com:babasoyturan/Redacta.git
    targetRevision: main
    path: deploy/helm/redacta
    helm:
      releaseName: redacta
      valueFiles:
        - values-gitops-local.yaml
        - versions.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: redacta
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
