apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: redacta-monitoring-local
  namespace: argocd
spec:
  description: Local monitoring GitOps project for Redacta
  sourceRepos:
    - https://prometheus-community.github.io/helm-charts
  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
